name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Gitea Package Registry
        uses: docker/login-action@v3
        with:
          registry: forge-gitea.global.dev.lwsa-idp-testbed.ingress.sh
          username: nobody
          password: ${{ secrets.GITEA_PACKAGE_REGISTRY_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            forge-gitea.global.dev.lwsa-idp-testbed.ingress.sh/user/app:latest
            forge-gitea.global.dev.lwsa-idp-testbed.ingress.sh/user/app:1.0.0