name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: tcp://localhost:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /certs/client
    steps:
      - name: Login to Gitea Package Registry
        uses: docker/login-action@v3
        with:
          registry: forge-gitea.global.dev.lwsa-idp-testbed.ingress.sh
          username: nobody
          password: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            forge-gitea.global.dev.lwsa-idp-testbed.ingress.sh/giba/python-web-app:latest
            forge-gitea.global.dev.lwsa-idp-testbed.ingress.sh/giba/python-web-app:1.0.0