name: ci

on:
  push:
    branches:
      - main
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
          
      - name: Login to Gitea Package Registry
        uses: docker/login-action@v3
        with:
          registry: https://forge-gitea.global.staging.platform-tools.ingress.sh
          username: nobody
          password: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            forge-gitea.global.staging.platform-tools.ingress.sh/gilberto.mautner/python-web-app:latest
